### ISSUE TITLE
anomalous dipole moment

### ISSUE THREAD

**Issue by lllx125** [bmad-sim/AtomicAndPhysicalConstants.jl#14]
find references for the dipole moment of a proton, a neutron, a deuteron, and He3 from PDG. Write a code to pull down the measured moment and get the anomalous part of it, returning a vector.

**Comment by lllx125** [comment]
I think there is no data for deuteron and He3, here are all the particles PDG have: https://pdg.lbl.gov/2023/mcdata/mass_width_2023.txt

**Comment by rot4te** [comment]
I'll handle this, I actually found the values I'm looking for
