### ISSUE TITLE
Changing units

### ISSUE THREAD

**Issue by rot4te** [bmad-sim/AtomicAndPhysicalConstants.jl#15]
We need to add functionality to change the units of all the constants to any other common unit.
The plan is to have all the constants stored in consistent units, (base eV), and use conversion to create temporary copies of the units in local memory. Since this total a few hundred Float64 objects, it won't take up more than a few kB

**Comment by DavidSagan** [comment]
I'm imagining a system where there is a function to set the units `set_units(who)` where `who` can be something like "MKS", "CGS", "ParticlePhysicsStandard" (is there a better name?), etc. I'm not sure of the best way to specify custom units.

**Comment by lllx125** [comment]
I want to clarify how this function works. Suppose someone uses the AtomicAndPhysicalConstants package and uses some variable, say print(m_electron). 
And it will print 0.51099895000e6 (in eV/c^2).
And say if they call the function set_units(Mev/c^2), then print(m_electron).
It will print 0.51099895000 (in MeV/c^2).
Is this what we are looking for?

**Comment by rot4te** [comment]
Yes, but that's the simple part.
You want to be able to convert to any unit of the same dimension: eg eV/c^2
to kg, with order (kilo, mega, giga, etc.) freedom as well.

For example the anomalous magnetic moments are expressed in nuclear
magnetons, but can also be thought of in Joule/Tesla or eV/Tesla, so it
would be nice to be able to express anomalous moments in MeV/Tesla

**Comment by lllx125** [comment]
ok

**Comment by DavidSagan** [comment]
@lllx125 Suggestion: Before coding, it's best to formulate the API (what the User sees) first. One thing to do is make a list of all the units for the physical constants. For example, some constants have units of speed (c_light), etc.

**Comment by mattsignorelli** [comment]
Also start with the more generic units like @DavidSagan said earlier (MKS, CGS, "ParticlePhysicsStandard" etc) because doing custom units (e.g. keV/c^2) will require parsing the units expression and we should all discuss the best way to do that when the time comes

**Comment by ChristopherMayes** [comment]
Also look at how openPMD stores units: https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md#unit-systems-and-dimensionality
This is completely general.

**Comment by lllx125** [comment]
Thanks
