### ISSUE TITLE
Anti-atoms

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/AtomicAndPhysicalConstants.jl#25]
Needed is a way to define antiatoms. My suggestion is to use an "anti_" prefix like "anti_He" rather than something like "He_bar" as not intuitive. Something like "antiHe" looks too jumbled. 

Also a function `antiparticle(particle)` is helpful. 

Note: The `massof` function when calculating the mass needs to take into account that for an anti-atom the nucleus is surrounded by positrons and not electrons.

**Comment by rot4te** [comment]
Functionality added
