### ISSUE TITLE
Expand Particle() function to take first arg string encoded with mass and charge.

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/AtomicAndPhysicalConstants.jl#26]
That is `Particle("#3He+")` and `Particle("C+3")` are handled along with the present syntax. This is useful since the user can then specify a particle using just a single string. Essentially, the `Particle` function can look for characters "#", "+", or "-" and split the string as appropriate.

**Comment by rot4te** [comment]
Done, used Regex to provide this functionality
