### ISSUE TITLE
Particle struct needs to record isotopic number for atoms

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/AtomicAndPhysicalConstants.jl#41]
One question that comes to mind is what to do with molecules where isotopic number is specified for some subset of the constituent atoms (EG heavy water). This edge case is not likely come up in the near future so it is not something we need an immediate answer to.

**Comment by rot4te** [comment]
I added an `iso::Int' field to the Species struct, and modified the constructor appropriately. 
Subatomic particles automatically have iso set to zero, and 'average mass' atoms get iso = -1
