### ISSUE TITLE
Use the name `Species` instead of `Particle`

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/AtomicAndPhysicalConstants.jl#45]
Motivation: Right now, `Particle` is the name of the structure holding the species info along with spin, charge state, etc. It does not (and should not) have information on "dynamic" properties like particle coordinates, state (dead/alive), etc. since that information will vary from tracking package to tracking package. My thinking is that it is most natural to use the name `Species` here and a tracking package can use the name `Particle` for a structure which will include `Species` and other information including coordinates, alive/dead state, etc. that fully describes the state of a single particle.

**Comment by rot4te** [comment]
Name is changed and pushed to source. I haven't touched references in setunits.jl due to ongoing work.
