### ISSUE TITLE
using `const` may cause problems if fundamental constants are switched on the fly.

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/AtomicAndPhysicalConstants.jl#67]
The problem will arise if fundamental constants are switched on the fly. In this case, functions that have compiled methods may retain the old values of the const globals. This needs to be checked. One possible solution is to not use `const` but rather fix the type of the globals using a `::XXX` suffix in the definition. This should ensure type stability.

**Comment by mattsignorelli** [comment]
Why would any of the `__b_` values be non-constant? I thought the point of the `__b_` was so that we had some constant base unit that didn't change?

**Comment by dtabell** [comment]
We want to be able to use, say, CODATA 2014. But do we want the ability to
do that “on the fly”?

**Comment by mattsignorelli** [comment]
We've resolved this using functions for the physical constants that are defined using `eval` in `setunits`
