### ISSUE TITLE
consider using renaming `massof` to `mass`, etc.

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/AtomicAndPhysicalConstants.jl#68]
I propose the following name changes:
- massof() -> mass()
- chargeof() -> charge()
- setunits(mass_unit, length_unit, time_unit, energy_unit, charge_unit) -> setunits(mass, length, time, energy, charge)

Any thoughts, comments?

**Comment by mattsignorelli** [comment]
Shouldn't the `Species` struct just store the `mass`, etc in the chosen units? It seems weird that we have calculate on the fly all of these units?

**Comment by DavidSagan** [comment]
But how to handle is a Species instance is created with one set of units and code using a different set of units tries to get the mass?

**Comment by mattsignorelli** [comment]
Ah, right, that makes sense

**Comment by DavidSagan** [comment]
Shall I close this issue?

**Comment by mattsignorelli** [comment]
Are the name changes pushed?

**Comment by DavidSagan** [comment]
Sorry I was confused. Ignore my last post.

**Comment by dtabell** [comment]
My only suggestion would be to reorder the arguments of setunits to (mass,
length, time, charge, energy).

Dan

**Comment by lllx125** [comment]
I think setunits(mass, length, time, charge, energy) is more consise

**Comment by DavidSagan** [comment]
OK so anyone feel free to make this change.

**Comment by lllx125** [comment]
changed massof()->mass, chargeof()->charge(), the stunt parameter are unchanged.
