### ISSUE TITLE
Unitful code added to physical_constants.jl should be elsewhere

### ISSUE THREAD

**Issue by rot4te** [bmad-sim/AtomicAndPhysicalConstants.jl#79]
Per Alex, Dan, and Lixing's conversation on 2024-10-03, the constants with a __b_ prefix should have unitful units, however there is setup code in the file as well, which is inappropriate. We'll discuss more in meeting at 2024-10-07 @1215

**Comment by lllx125** [comment]
done in the branch new_setunits
