### ISSUE TITLE
Rename Species mass field

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/AtomicAndPhysicalConstants.jl#81]
One mistake I can see people making is to use `species.mass` instead of `mass(species)` and then wondering what went wrong. To help avoid this, I propose modifying the `mass` field of the Species struct. So instead of `species.mass` use the name `species.mass_in_std_units` (or any other name that is descriptive).

**Comment by rot4te** [comment]
I renamed the struct field in the most recent PR for branch '75+-edit_species_mass_unit', but I haven't renamed the same field in either the atomic or subatomic species dictionaries. Should I?

**Comment by DavidSagan** [comment]
@rot4te Yes a rename in atomic and subatomic species dicts would make things clearer.

**Comment by DavidSagan** [comment]
Thinking about it, a rename of the other fields of `Species` would make things clearer.
