### ISSUE TITLE
Make `setunits` return the current `UnitSystem` type, remove print

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/AtomicAndPhysicalConstants.jl#91]
The `setunits` function should return the `UnitSystem` stored in the global type `current_units`. Then you can provide an overload for `show` for the `UnitSystem` type to look like `printunits` and remove the `print_units` flag. Then the user can choose to print it afterwards without having this flag

**Comment by lllx125** [comment]
done in branch 88-fix_global_varible_type
